version: '3.2'

services:
  portfolio:
    build: .
    command: python ./resume/manage.py runserver 0.0.0.0:80
#    command: python manage.py runserver 0.0.0.0:${SERVER_PORT}
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/code
    networks:
      - webnet

networks:
    webnet:
