version: '3.2'

services:
  portfolio:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
#    command: python manage.py runserver 0.0.0.0:${SERVER_PORT}
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    networks:
      - webnet

networks:
    webnet:
